---
# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/user/application_security/sast/#available-cicd-variables
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure/
# Dependency Scanning customization: https://docs.gitlab.com/user/application_security/dependency_scanning/#customizing-analyzer-behavior
# Container Scanning customization: https://docs.gitlab.com/user/application_security/container_scanning/#customizing-analyzer-behavior
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ci/variables/#cicd-variable-precedence
stages:
- secret-detection
- test
variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: secret-detection
include:
- template: Security/Secret-Detection.gitlab-ci.yml

check:
  image: docker.io/ubuntu:26.04
  stage: test
  script:
    - apt-get -qq -y update
    - DEBIAN_FRONTEND=nonineractive apt -qq -y install make sudo
    - make deb-deps
    - make vim-deps
    - make check
    - make stow
    - make test-stow
