name: check
on: [push]
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: make deb-deps
      - name: Install more dependencies
        run: make vim-deps
      - name: Run checks
        run: make check
      - name: Run installation
        run: make stow
      - name: test installation
        run: make test-stow
